apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
spec:
  destination:
    name: ''
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: ./environment-promotion/envs/staging
    repoURL: 'https://github.com/ywy50/gitops-cert-level-2-examples'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
